# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rabbitmuncher
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: bok
# "service" is the name of this project. This will also be added to your AWS resource names.
service: bok

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 60

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
