# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rabbitmuncher
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: bok
# "service" is the name of this project. This will also be added to your AWS resource names.
service: bok

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 30

functions:
  api:
    handler: src/handler.function
    environment:
      DATABASE_PASSWORD: ${aws:ssm:/inspections/rds_password}
      DATABASE_USER: ${aws:ssm:/inspections/rds_user}
      DATABASE_HOST: ${aws:ssm:/inspections/rds_host}
    events:
      - httpApi: "*"
